### ISSUE TITLE
Restrictions on names

### ISSUE THREAD

**Issue by sergutsan** [SophieKoonin/JavaDecaf#19]
At the moment, JavaDecaf restricts the choice of name for the main JavaDecaf program: it must start with a capital letter. 

This seems to be a good idea, and I think it could be extended to all names in the code: 
- The program name must start with a capital letter
- Class names must always start with a capital letter
- Variable names must always start with a non-capital letter. 
- Method names must always start with a non-capital letter. 
- Neither class, method, nor variable names can start with an underscore (_)

The benefits of the first four points is encouraging good practice and common conventions in students since Day 1. 

The benefit of the fifth point is that it prevents clashes with JavaDecaf´s internal variables, such as `__reader` (we had a clash with `input` the other day and the student was very confused and disappointed because their code "was correct!").

**Comment by sophiekoonin** [comment]
Currently, it does (or at least should) check class names, method names and
variable names for correct capitalisation, through the methods checkVariableName, checkMethodName, checkClassName. Shouldn't be too hard to check
for starting with an underscore.

**Comment by sergutsan** [comment]
Thanks!

Will double check that because I keep telling students not to start method names with capital letters. 

Will also look into the underscores when I can.

**Comment by sergutsan** [comment]
A question from a student makes me think to take things a bit further: 
- Method names must always start with a non-capital letter. 
  - Method names must not be the same as either of the methods of Object.java
    - **clone()**
    - **equals(Object obj)**
    - finalize()
    - getClass()
    - hashCode()
    - notify()
    - notifyAll()
    - **toString()**
    - wait()

Most are unlikely to happen but not the ones in bold. When students try to (unconsciously) overwrite them with a different return value, the Java compiler complains and the students get confused.

**Comment by sergutsan** [comment]
Implemented in d6221c59c, df422ec5, and 01e8ee9a.
