### ISSUE TITLE
JavaDecaf does not accept System.console().readLine()

### ISSUE THREAD

**Issue by sergutsan** [SophieKoonin/JavaDecaf#3]
The Java Decaf code...

```
String s = System.console().readLine();
```

...should produce the following Java code...

```
String s = System.console().readLine();
```

...but produces this instead: 

```
String s = System.console()();
```

**Comment by sophiekoonin** [comment]
Fixed in 6c88a98476bc55e27af3c105b55143057064bb22. For some reason it was ignoring any cases of "." followed by an identifier. Not any more!
