### ISSUE TITLE
JavaDecaf does not accept method calls with more than one parameter

### ISSUE THREAD

**Issue by sergutsan** [SophieKoonin/JavaDecaf#4]
The code...

```
String input2 = readLine();
println(input2.substring(0, 2));
```

should produce the following code...

```
String input2 = input.next();
System.out.println(input2.substring(0, 2));
```

...but produces the following code instead...

```
String input2 = input.next();
System.out.println(input2.substring(0 2));
```

A comma is missing between both parameters. I guess there must be something wrong in the AST somewhere.

**Comment by sergutsan** [comment]
Trying to fix this now before the lecture on methods.

**Comment by sergutsan** [comment]
More info. Apparently it is unrelated to the number of params (any number above 1 reproduces the problem) and whether the method is local or part of the main API. 

```
String input2 = readLine();
aaa(1,1,1);

void aaa(int i, int ii, int iii) {
    return;
}
```

produces 

```
    public static void main(String[] args) {
        String input2 = input.next();
        aaa(111);
    }

    private static void aaa(int i, int ii, int iii) {
        return;
    }
```

**Comment by sergutsan** [comment]
Simplest code to reproduce this error: 

```
println("abc".substring(0, 2)); // only line in .jdc file
```

should produce 

```
System.out.println("abc".substring(0, 2)); // surrounded by psvm, etc
```

but produces

```
System.out.println("abc".substring(0 2)); // surrounded by psvm, etc
```

**Comment by sergutsan** [comment]
Compiling with -d shows that the comma is consumed: 

```
 Consumed token: <"," at line 1 column 26>
```

but it is apparently lost / discarded / ignored at a later stage before writing into the .java file.

**Comment by sergutsan** [comment]
An even simpler program to reproduce the error (shorter program -> shorter trace): 

```
Math.pow(1,1);
```

It is worth noting that this problem only affects method calls (i.e. arguments) and not method declarations (i.e. positional parameter list). The latter do not seem to lose any comma, only the former.

**Comment by sergutsan** [comment]
Apparently ASTComma.process() is never called, even when compiling code such as: 

```
Math.pow(1,1);  

int aaa(int i, int ii, int iii){
  return 1;
}
```

The method declaration does not lose the commas, so they must be printed somewhere. 

Have I been following a red herring all along? Where are those comma-tokens printed, i.e. written into the output-java-file?

**Comment by sergutsan** [comment]
Printing every token from the former program returns this: 

```
Image: Math
Image: .
Image: pow
Image: (
Image: 1
Image: 1       <---- comma missing!
Image: )
Image: ;
Image:     }
Image: int
Image: i
Image: ,
Image: int
Image: ii
Image: ,
Image: int
Image: iii
...  
```

...so the comma is actually lost at some point. Looking at the tokens one by one, there are only two tokens whose image contains ",", so it does not seem to be a problem of commas in arguments list being marked as "special" or anything like that. The problem seems to be that (a) the token is not added to the tree or that (b) it is added but then removed at a later point. My money is on (a).

**Comment by sergutsan** [comment]
Three commas are consumed, three commas pass through  JDCParser.jj_consume_token(int) without error or exception, as it should be. Where is the first one of them lost?

**Comment by sophiekoonin** [comment]
Hopefully fixed with commit b2c21c8c78f54cf5881417c720a8e4d1fe90c553 - the commas were being parsed but then nothing done with them. Told it to create a comma node for each comma it found in nonterminal ArgumentList(). 

Method parameters in definitions have a separate nonterminal, hence why they didn't have the same problem.

**Comment by sergutsan** [comment]
Cannot reproduce anymore, so closing. Thanks Sophie for the work and this and the other issues.

**Comment by sergutsan** [comment]
I reopen this issue because apparently it is not closed. 

```
 $ cat Rock.jcd 
 "Some string".substring(0, 1); 
 $ javadecaf Rock.jcd 
 JavaDecaf: Compiling file Rock.jcd... 
 Rock.java:8: error: ')' expected
          "Some string".substring(0 1);
                                  ^
 Rock.java:8: error: illegal start of expression
         "Some string".substring(0 1);
                                    ^
 2 errors
 JavaDecaf: Compilation finished in 24 ms
```

**Comment by sergutsan** [comment]
It seems there has been a regression. I am looking into it. Thank God for version control. Worst-case scenario, we should be able to roll back. 

I reopen this issue because apparently it is not closed. 

```
$ cat Rock.jcd 
Math.pow(2,2);
$ javadecvaf Rock.jcd 
JavaDecaf: Compiling file Rock.jcd...
Rock.java:10: error: method pow in class Math cannot be applied to given types;
            Math.pow(22);
                ^
  required: double,double
  found: int
  reason: actual and formal argument lists differ in length
1 error
JavaDecaf: Compilation finished in 24 ms
```

**Comment by sergutsan** [comment]
It is clearly a regression. Commit 29008c627c895439d fixes the problem. 

There must have been a mistake either when merging or when publishing (changing version numbers on mvn?). 

Should be easy to fix. I am on it.

**Comment by sergutsan** [comment]
Strange. Could not replicate again. I have tested the software on every commit up to the most recent one and it works on each and every one of them. Maybe there was some spurious error in the build that was deployed on Friday?

Closing again because issue cannot be replicated.
